# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWIndow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(763, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBoxLA = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxLA.setObjectName("comboBoxLA")
        self.comboBoxLA.addItem("")
        self.comboBoxLA.addItem("")
        self.comboBoxLA.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxLA)
        self.pushButtonAnalyse = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonAnalyse.setCheckable(False)
        self.pushButtonAnalyse.setChecked(False)
        self.pushButtonAnalyse.setObjectName("pushButtonAnalyse")
        self.horizontalLayout.addWidget(self.pushButtonAnalyse)
        self.radioButtonRestart = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButtonRestart.setChecked(True)
        self.radioButtonRestart.setObjectName("radioButtonRestart")
        self.horizontalLayout.addWidget(self.radioButtonRestart)
        spacerItem1 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEditInfo = QtWidgets.QTextEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.textEditInfo.setFont(font)
        self.textEditInfo.setObjectName("textEditInfo")
        self.gridLayout_2.addWidget(self.textEditInfo, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonDB = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDB.setObjectName("pushButtonDB")
        self.horizontalLayout_2.addWidget(self.pushButtonDB)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusbar.setPalette(palette)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBoxLA.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FluDoPy"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Settings"))
        self.comboBoxLA.setToolTip(_translate("MainWindow", "M/C on which beams were delivered for QA"))
        self.comboBoxLA.setItemText(0, _translate("MainWindow", "LA1"))
        self.comboBoxLA.setItemText(1, _translate("MainWindow", "LA3"))
        self.comboBoxLA.setItemText(2, _translate("MainWindow", "LA4"))
        self.pushButtonAnalyse.setText(_translate("MainWindow", "Analyse"))
        self.radioButtonRestart.setToolTip(_translate("MainWindow", "Scans for new dynalogs if checked and when analyzed is clicked"))
        self.radioButtonRestart.setText(_translate("MainWindow", "Restart session"))
        self.groupBox.setTitle(_translate("MainWindow", "Information"))
        self.pushButtonDB.setText(_translate("MainWindow", "Push to database"))

