[tool.poetry]
name = "pymedphys_workshops"
version = "0.1.0"
description = ""
authors = ["Simon Biggs <me@simonbiggs.net>"]
license = "AGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
