MATURE = "Mature"
PRODUCTION_STABLE = "Production/Stable"
BETA = "Beta"
ALPHA = "Alpha"
PRE_ALPHA = "Pre-Alpha"
PLANNING = "Planning"

APPLICATION_CATEGORIES_BY_COLUMN = {
    0: [MATURE, PRODUCTION_STABLE],
    1: [BETA, ALPHA],
    2: [PRE_ALPHA, PLANNING],
}
