MATURE = "Mature"
PRODUCTION_STABLE = "Production/Stable"
BETA = "Beta"
ALPHA = "Alpha"
PRE_ALPHA = "Pre-Alpha"
PLANNING = "Planning"


APPLICATION_CATEGORIES = [MATURE, PRODUCTION_STABLE, BETA, ALPHA, PRE_ALPHA, PLANNING]
