TOLERANCE_TYPES = {
    1: "Standard",
    2: "Hexapod",
    3: "electrons",
    4: "IMRT",
    5: "zz-breast",
    6: "Large Pt",
    7: "zz-CSA/Spine",
    8: "zz-Peacock",
    9: "zz-SRS/SBRT",
    10: "Zero Tolerance",
    11: "zz-Installer",
    12: "Novalis",
    13: "CBCT",
    14: "zz-Brain and HN",
    15: "Vault 6HD Table",
    16: "Vault 6HD Maximum",
    17: "zz-Exactrac",
    18: "Vault 2HD Table",
    19: "Vault 2HD Maximum",
    20: "Vault 4HD Table",
    21: "Vault 4HD Maximum",
}

SITE_CONSTANTS = {
    0: "Unknown",
    1: "VOID",
    2: "CLOSE",
    3: "COMPLETE",
    4: "HOLD",
    5: "APPROVE",
    6: "PROCESS_LOCK",
    7: "PENDING",
}
