# Copyright (C) 2026 Matthew Jennings

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""``pymedphys --version`` reports the installed distribution's version."""

import importlib.metadata
import subprocess
import sys

import pymedphys


def test_version_matches_the_installed_metadata():
    # _version.py is generated by `pymedphys dev propagate`; a stale copy
    # would make the CLI and the package index disagree.
    assert pymedphys.__version__ == importlib.metadata.version("pymedphys")


def test_version_flag_prints_the_version_and_exits_cleanly():
    result = subprocess.run(
        [sys.executable, "-m", "pymedphys", "--version"],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert result.stdout == f"pymedphys {importlib.metadata.version('pymedphys')}\n"
