# Copyright (C) 2026 Matthew Jennings

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Malformed input to the parsers of untrusted bytes, generated by Hypothesis.

The file reader (:mod:`.file_layout`), the codestream parsers
(:mod:`.codestreams` and :mod:`.frame_headers`), and the JPEG 2000 packet
reader (:mod:`.jpeg_2000_packets`) read bytes that anyone can write. Each
test here mutates synthetic files and codestreams, or writes structures
from random parameters, and requires that the parser either reads them or
refuses them as it documents: it never raises anything else, never takes
time out of proportion to the input, and accounts for every byte, so that
the residual search is never pointed past one. The last test runs whole
instances through the transform and the release gate, and requires that a
released file never holds the source's name, planted anywhere in it.

CI runs Hypothesis's default number of examples. A longer campaign runs the
same tests with the ``deid-fuzz`` profile of the root conftest::

    pymedphys dev tests tests/dicom/test_deidentify_malformed_input.py \\
        --hypothesis-profile=deid-fuzz --hypothesis-seed=1
"""

import functools
import struct

from pymedphys._imports import hypothesis
from pymedphys._imports import numpy as np
from pymedphys._imports import pytest

from pymedphys._dicom.deidentify import (
    codestreams,
    frame_headers,
    jpeg_2000_packets,
    pixel_decoding,
)
from pymedphys._dicom.deidentify.codestreams import CodestreamRefused
from pymedphys._dicom.deidentify.file_layout import (
    Region,
    read_file_layout,
    reads_as_items,
)
from pymedphys._dicom.deidentify.instance_transform import (
    InstanceTransform,
    ReleaseGate,
)
from pymedphys._dicom.deidentify.keys import DeidKey
from pymedphys._dicom.deidentify.policy import compose_policy
from pymedphys._dicom.deidentify.reasons import TransformReason
from pymedphys._dicom.deidentify.references import InstanceRecord
from pymedphys._dicom.deidentify.release_gate import Coverage
from pymedphys._dicom.deidentify.run_results import Release, Sequestered, Transformed
from pymedphys._dicom.deidentify.source import (
    SourceEvidence,
    SourceRefused,
    read_source,
)

from . import _synthetic_compressed as compressed
from . import _synthetic_jpeg_2000 as synthetic_j2k
from . import _synthetic_references as synthetic
from .test_deidentify_file_layout import HAND_BUILT

st = hypothesis.strategies
pytestmark = pytest.mark.pydicom

IMPLICIT = "1.2.840.10008.1.2"
EXPLICIT = "1.2.840.10008.1.2.1"
J2K_LOSSLESS = "1.2.840.10008.1.2.4.90"
J2K = "1.2.840.10008.1.2.4.91"
ENCAPSULATED = sorted(
    {*codestreams._JPEG, *codestreams._JPEG_LS, *codestreams._JPEG_2000}  # pylint: disable = protected-access
)
# An invented name, long enough to be searched for in entropy-coded data.
NAME = "ZEBEDEE^QUILLON"
NEEDLES = (b"ZEBEDEE^QUILLON", b"ZEBEDEEQUILLON", b"QUILLONZEBEDEE")
KEY = DeidKey(bytes(range(32)))
# Values that make lengths, counts, and offsets wrong in interesting ways.
INTERESTING = (0, 1, 2, 0x7F, 0x80, 0xFF, 0x100, 0x7FFF, 0xFFFF, 0x10000, 0xFFFFFFFF)
SETTINGS = hypothesis.settings(
    deadline=None,
    suppress_health_check=[hypothesis.HealthCheck.too_slow],
)


@st.composite
def mutated(draw, seeds, near=b""):
    """Draw a seed, then change it a few times: flip, set, insert, delete, or
    duplicate bytes, write an interesting integer, or truncate it.

    Half the changes are made just after an occurrence of ``near``, such as
    0xFF before a marker, so that headers are changed more often than the
    bulk data between them.
    """
    data = bytearray(draw(st.sampled_from(seeds)))
    marks = [i for i in range(len(data)) if near and data.startswith(near, i)]
    for _ in range(draw(st.integers(1, 6))):
        if marks and draw(st.booleans()):
            mark = draw(st.sampled_from(marks))
            at = min(mark + draw(st.integers(0, 8)), len(data))
        else:
            at = draw(st.integers(0, len(data)))
        change = draw(
            st.sampled_from(
                ["flip", "set", "insert", "delete", "duplicate", "integer", "truncate"]
            )
        )
        if change == "flip" and at < len(data):
            data[at] ^= 1 << draw(st.integers(0, 7))
        elif change == "set" and at < len(data):
            data[at] = draw(st.integers(0, 255))
        elif change == "insert":
            data[at:at] = draw(st.binary(min_size=1, max_size=16))
        elif change == "delete":
            del data[at : at + draw(st.integers(1, 16))]
        elif change == "duplicate":
            data[at:at] = data[at : at + draw(st.integers(1, 64))]
        elif change == "integer":
            form = draw(st.sampled_from(["<H", "<I", ">H", ">I"]))
            value = draw(st.sampled_from(INTERESTING)) % (
                1 << 8 * struct.calcsize(form)
            )
            data[at : at + struct.calcsize(form)] = struct.pack(form, value)
        elif change == "truncate":
            del data[at:]
    return bytes(data)


def _ct(frame=None):
    """A CT slice of ``NAME``, with ``frame`` as native Pixel Data."""
    dataset = synthetic.ct_slice(0)
    dataset.PatientName = NAME
    if frame is not None:
        dataset.SamplesPerPixel = 1
        dataset.PhotometricInterpretation = "MONOCHROME2"
        dataset.Rows, dataset.Columns = frame.shape
        dataset.BitsAllocated, dataset.BitsStored, dataset.HighBit = 16, 12, 11
        dataset.PixelRepresentation = 0
        dataset.PixelData = frame.astype("<u2").tobytes()
    return dataset


@functools.lru_cache(maxsize=None)
def _files():
    """Synthetic files of the structures the reader reads: nested sequences,
    implicit VR, native and encapsulated Pixel Data, and Data Set Trailing
    Padding."""
    files = [
        HAND_BUILT,
        synthetic.written(_ct()),
        synthetic.written(synthetic.rt_plan()),
        synthetic.written(synthetic.rt_plan(), IMPLICIT),
        synthetic.written(synthetic.structure_set()),
        synthetic.written(synthetic.rt_dose()),
    ]
    return tuple(files + [data for _, data in _images()])


@functools.lru_cache(maxsize=None)
def _frame():
    return (np.arange(32 * 32, dtype=np.uint16).reshape(32, 32) * 37) % 4096


@functools.lru_cache(maxsize=None)
def _images():
    """CT images, as ``(syntax, file)``, in each syntax that the tests here
    can encode, with a comment and an application segment in each JPEG
    codestream and a comment in each JPEG 2000 one, and with several frames
    found by a Basic Offset Table, by an Extended Offset Table, and by
    parsing the fragments."""
    frame = _frame()
    jpeg = compressed._with_jpeg_text(  # pylint: disable = protected-access
        compressed.jpeg_lossless(frame, precision=12), "SYNMK"
    )
    three = [jpeg] * 3
    starts = compressed.frame_starts(three)
    lengths = [len(c) + len(c) % 2 for c in three]
    image = functools.partial(
        compressed.ct_image, rows=32, columns=32, bits=12, name=NAME
    )
    sv1 = compressed.JPEG_LOSSLESS_SV1
    images = [
        (EXPLICIT, synthetic.written(_ct(frame))),
        (compressed.RLE_LOSSLESS, compressed.rle_ct_image(frame, name=NAME)),
        (sv1, image(sv1, [jpeg])),
        (sv1, image(sv1, three, number_of_frames=3, offsets=starts)),
        (sv1, image(sv1, three, number_of_frames=3, extended=(starts, lengths))),
        (sv1, image(sv1, [b"".join(three)], number_of_frames=3)),
    ]
    for syntax, codestream in _jpeg_2000_codestreams().items():
        images.append((syntax, image(syntax, [codestream])))
    return tuple(images)


@functools.lru_cache(maxsize=None)
def _jpeg_2000_codestreams():
    """pylibjpeg-openjpeg's codestreams, lossless and lossy, keyed by syntax,
    or none where it is not installed."""
    try:
        import openjpeg  # pylint: disable = import-outside-toplevel, import-error, unused-import
    except ImportError:
        return {}
    frame = _frame()
    return {
        J2K_LOSSLESS: compressed.jpeg_2000(frame, precision=12),
        J2K: compressed.jpeg_2000(frame, precision=12, compression_ratios=[20, 5, 1]),
    }


@functools.lru_cache(maxsize=None)
def _codestreams():
    """JPEG and JPEG 2000 codestreams, keyed by an encapsulating syntax."""
    lossless = compressed.jpeg_lossless(_frame(), precision=12)
    found = {
        compressed.JPEG_LOSSLESS_SV1: [
            lossless,
            compressed._with_jpeg_text(lossless, "SYNMK"),  # pylint: disable = protected-access
        ],
        compressed.JPEG_EXTENDED: [compressed.jpeg_extended_mid_grey(8, 8)],
        J2K_LOSSLESS: list(_packet_codestreams()),
    }
    for syntax, codestream in _jpeg_2000_codestreams().items():
        found.setdefault(syntax, []).append(codestream)
    return {syntax: tuple(each) for syntax, each in found.items()}


@functools.lru_cache(maxsize=None)
def _packet_codestreams():
    """Codestreams whose packet headers the synthetic writer gives: Part 1
    and HT code-blocks, several layers, SOP and EPH markers, and the
    code-block styles that change how codeword segments are counted."""
    contribution, write = synthetic_j2k.contribution, synthetic_j2k.codestream
    planes = synthetic_j2k.MAGNITUDE_BIT_PLANES
    full = 3 * planes - 2
    four = [contribution((full, 5))] * 4
    return (
        write([four], [0, 0, 0, 0], size=(16, 16)),
        write(
            [[contribution((10, 3))] * 4, [contribution((full - 10, 4))] * 4],
            [0, 0, 0, 0],
            size=(16, 16),
            scod=synthetic_j2k.SOP | synthetic_j2k.EPH,
        ),
        write(
            [[contribution((10, 50), (2, 3), (1, 4), (2, 5), (1, 6), (2, 7), (1, 8))]],
            [2],
            style=synthetic_j2k.BYPASS,
        ),
        write(
            [[contribution(*[(1, 3)] * (3 * (planes - 2) - 2))]],
            [2],
            style=synthetic_j2k.TERMINATE_ALL,
        ),
        write([[contribution((1, 30), (2, 4))]], [planes - 2], style=synthetic_j2k.HT),
    )


def _all_codestreams():
    return tuple(c for each in _codestreams().values() for c in each)


def _check_layout(layout, data):
    """Check that the layout accounts for every byte of ``data`` once, and
    that each element it read is where its spans are."""
    assert layout.size == len(data)
    spans = layout.spans
    if not data:
        assert spans == ()
        return
    assert spans[0].start == 0
    assert spans[-1].end == len(data)
    for before, after in zip(spans, spans[1:]):
        assert before.end == after.start
    for span in spans:
        assert span.start < span.end
        if span.value_start is not None:
            assert span.start <= span.value_start <= span.end
    if layout.readable:
        assert Region.TRAILING not in {span.location.region for span in spans}
    starts = [span.start for span in spans]
    for extent in layout.elements:
        assert 0 <= extent.start <= extent.value_start <= extent.end <= len(data)
        path = extent.location.element
        inside = spans[starts.index(extent.start) :]
        for span in inside:
            if span.start >= extent.end:
                break
            element = span.location.element
            # Each span of an element is the element's own, or of one in
            # its items.
            assert element == path or (
                element.items[: len(path.items)] == path.items
                and len(element.items) > len(path.items)
                and element.items[len(path.items)][0] == path.tag
            )
    for offset in sorted({0, len(data) // 2, len(data) - 1}):
        span = next(s for s in spans if s.start <= offset < s.end)
        assert layout.locate(offset) == span.location


@SETTINGS
@hypothesis.given(st.one_of(mutated(_files()), st.binary(max_size=512)))
def test_the_reader_accounts_for_every_byte_of_any_file(data):
    try:
        layout = read_file_layout(data)
    except ValueError:  # a deflated data set, as documented
        return
    _check_layout(layout, data)


@SETTINGS
@hypothesis.given(st.binary(max_size=256), st.booleans(), st.booleans())
def test_any_value_is_read_as_items_or_not(value, explicit, nested):
    assert reads_as_items(value, explicit=explicit, nested=nested) in (True, False)


@SETTINGS
@hypothesis.given(mutated(_files()))
def test_any_file_is_read_as_a_source_or_refused(data):
    try:
        source = read_source(data)
    except SourceRefused:
        return
    assert isinstance(source, SourceEvidence)


def _check_ranges(ranges, data):
    assert ranges == sorted(ranges)
    for start, stop in ranges:
        assert 0 <= start <= stop <= len(data)
    for (_, stop), (start, _) in zip(ranges, ranges[1:]):
        assert stop <= start


def _jpeg_scan_bytes_are_data(syntax, data, ranges):
    """Return whether each 0xFF in the ranges, and any fill bytes after it,
    is followed by a stuffed byte or a restart marker, so that no marker
    segment, which could hold text, is taken as entropy-coded data."""
    ls = syntax in codestreams._JPEG_LS  # pylint: disable = protected-access
    for start, stop in ranges:
        position = data.find(b"\xff", start, stop)
        while position >= 0:
            following = position + 1
            while following < stop and data[following] == 0xFF:
                following += 1
            if following == stop:
                return False
            byte = data[following]
            stuffed = following == position + 1 and (byte < 0x80 if ls else byte == 0)
            if not (stuffed or 0xD0 <= byte <= 0xD7):
                return False
            position = data.find(b"\xff", following + 1, stop)
    return True


@SETTINGS
@hypothesis.given(st.sampled_from(ENCAPSULATED), st.data())
def test_entropy_coded_data_are_found_in_any_codestreams_or_none(syntax, data):
    joined = data.draw(
        st.one_of(
            mutated(_all_codestreams(), near=b"\xff"),
            st.lists(mutated(_all_codestreams(), near=b"\xff"), max_size=3).map(
                b"".join
            ),
        )
    )
    ranges = codestreams.entropy_coded(syntax, joined)
    if ranges is None:
        return
    _check_ranges(ranges, joined)
    if syntax not in codestreams._JPEG_2000:  # pylint: disable = protected-access
        assert _jpeg_scan_bytes_are_data(syntax, joined, ranges)


@SETTINGS
@hypothesis.given(st.sampled_from(ENCAPSULATED), st.data())
def test_any_codestream_is_cut_or_refused_and_a_cut_leaves_nothing_to_cut(syntax, data):
    frame = data.draw(mutated(_all_codestreams(), near=b"\xff"))
    try:
        cut = codestreams.cut_codestream(syntax, frame)
    except CodestreamRefused as refused:
        assert refused.reason in (
            TransformReason.UNPARSABLE_CODESTREAM,
            TransformReason.UNCUTTABLE_METADATA,
        )
        return
    if cut is None:
        return
    assert len(cut) < len(frame)
    assert codestreams.cut_codestream(syntax, cut) is None
    assert codestreams.entropy_coded(syntax, cut) is not None


@SETTINGS
@hypothesis.given(mutated(_files(), near=b"\xfe\xff\x00\xe0"))
def test_any_pixel_data_is_cut_or_refused(data):
    try:
        source = read_source(data)
    except SourceRefused:
        return
    # The transform cuts only frames that decode and match their attributes.
    if pixel_decoding.frames_problem(source) is not None:
        return
    try:
        value = codestreams.without_metadata(source)
    except CodestreamRefused:
        return
    assert value is None or isinstance(value, bytes)


DECLARED = frame_headers.Declared(32, 32, 1, 12, False, "MONOCHROME2")


@SETTINGS
@hypothesis.given(st.sampled_from(ENCAPSULATED), st.data())
def test_any_frame_header_matches_or_gives_a_reason(syntax, data):
    frame = data.draw(mutated(_all_codestreams(), near=b"\xff"))
    problem = frame_headers.header_problem(syntax, frame, DECLARED)
    assert problem is None or isinstance(problem, TransformReason)


@SETTINGS
@hypothesis.given(
    mutated(
        _packet_codestreams() + tuple(_jpeg_2000_codestreams().values()), near=b"\xff"
    )
)
def test_any_packets_are_read_or_not(codestream):
    assert jpeg_2000_packets.coding_passes_kept(codestream) in (True, False, None)


def _segment(code, payload):
    return struct.pack(">BBH", 0xFF, code, len(payload) + 2) + payload


@st.composite
def _structures(draw):
    """A codestream of one tile-part whose SIZ, COD, and QCD are drawn, with a
    body of random bytes, so that the geometry of tiles, resolutions,
    precincts, and code-blocks is drawn too."""
    sides = st.one_of(
        st.integers(1, 64), st.integers(1, 0xFFFF), st.sampled_from([4096, 0xFFFF])
    )
    columns, rows = draw(sides), draw(sides)
    tile = draw(st.sampled_from([0, 1 << 15, 1 << 10, 64]))
    tile_columns, tile_rows = (columns, rows) if not tile else (tile, tile)
    components = draw(st.integers(1, 3))
    levels = draw(st.integers(0, 8))
    scod = draw(st.integers(0, 7))
    precincts = bytes(
        draw(st.lists(st.integers(0, 255), min_size=levels + 1, max_size=levels + 1))
    )
    cod = struct.pack(
        ">BBHB", scod, draw(st.integers(0, 4)), draw(st.integers(1, 64)), 0
    )
    cod += bytes(
        [
            levels,
            draw(st.integers(0, 8)),
            draw(st.integers(0, 8)),
            draw(st.sampled_from([0, 0x01, 0x04, 0x40])),
            1,
        ]
    )
    cod += precincts if scod & 1 else b""
    qcd = bytes([2 << 5]) + bytes([8 << 3] * (3 * levels + 1))
    body = draw(st.binary(max_size=256))
    tile_part = struct.pack(">HIBB", 0, 12 + 2 + len(body), 0, 1)
    size = struct.pack(
        ">H8IH", 0, columns, rows, 0, 0, tile_columns, tile_rows, 0, 0, components
    )
    return b"".join(
        [
            b"\xff\x4f",
            _segment(0x51, size + bytes([11, 1, 1]) * components),
            _segment(0x52, cod),
            _segment(0x5C, qcd),
            _segment(0x90, tile_part),
            b"\xff\x93",
            body,
            b"\xff\xd9",
        ]
    )


@SETTINGS
@hypothesis.given(_structures())
def test_packets_of_any_geometry_are_read_or_not(codestream):
    assert jpeg_2000_packets.coding_passes_kept(codestream) in (True, False, None)


@functools.lru_cache(maxsize=None)
def _transform():
    return InstanceTransform(compose_policy("basic"), KEY, unvalidated_policy=True)


def _decodable_images():
    """The images whose Pixel Data is native or can be decoded here."""
    return tuple(
        data
        for syntax, data in _images()
        if syntax not in pixel_decoding.DECODING_PLUGINS
        or pixel_decoding.decoder_available(syntax)
    )


@st.composite
def _planted(draw):
    """A mutated image, with one of the name's forms written over some of its
    bytes, between NULs, so that no rule of the search for text, such as one
    that a letter beside a name makes it part of a longer word, excuses it."""
    data = bytearray(draw(mutated(_decodable_images(), near=b"\xff")))
    needle = b"\x00" + draw(st.sampled_from(NEEDLES)) + b"\x00"
    at = draw(st.integers(0, max(len(data) - len(needle), 0)))
    data[at : at + len(needle)] = needle
    return bytes(data)


def _collected_name(evidence):
    coverage = evidence.coverage if hasattr(evidence, "coverage") else evidence
    if not isinstance(coverage, Coverage):
        return False
    return any(
        str(value.source) == "(0010,0010)" and str(value.value) == NAME
        for value in coverage.collected
    )


# A fifth of the profile's examples, since each runs a whole instance.
@hypothesis.settings(SETTINGS, max_examples=max(SETTINGS.max_examples // 5, 20))
@hypothesis.given(st.one_of(_planted(), mutated(_decodable_images(), near=b"\xff")))
def test_an_image_is_transformed_or_withheld_and_a_release_holds_no_name(data):
    try:
        record = InstanceRecord.from_file(data)
    # The run refuses or sequesters a file whose record cannot be read.
    except Exception:  # pylint: disable = broad-exception-caught
        return
    result = _transform()(data, record)
    assert isinstance(result, (Transformed, Sequestered))
    if not isinstance(result, Transformed):
        return
    verdict = ReleaseGate()(result.data, result.evidence, (result.evidence,))
    if isinstance(verdict, Release) and _collected_name(result.evidence):
        written = result.data.upper()
        assert not any(needle in written for needle in NEEDLES)
