name: Actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/actions/**/action.yml'
  push:
    branches: [main]
    paths:
      - '.github/workflows/*.yml'
      - '.github/actions/**/action.yml'

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - name: Run actionlint
        uses: rhysd/actionlint@a52854e7e09cdb580ab549fbb3f0a46dc2e55942 # 1.7.7
