name: Documentation

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        default: true
        required: false
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'lib/pymedphys/docs/**'
      - '*.md'
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        default: true
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-project
        with:
          extras: 'docs'

      - name: Download required data
        run: |
          uv run python -c "
          import pymedphys
          pymedphys.data_path('original_dose_beam_4.dcm')
          pymedphys.data_path('logfile_dose_beam_4.dcm')
          "

      - name: Build documentation
        run: |
          uv run pymedphys dev docs

          # Check for broken links
          uv run python -m sphinx.ext.linkcheck lib/pymedphys/docs || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: lib/pymedphys/docs/_build/html

  deploy:
    needs: [build]
    if: ${{ inputs.publish }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
