name: Documentation

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        default: true
        required: false
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        default: true
        required: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - uses: ./.github/actions/setup-project
        with:
          extras: "docs"

      - name: Download required data
        run: |
          uv run python -c "import pymedphys; pymedphys.data_path('original_dose_beam_4.dcm'); pymedphys.data_path('logfile_dose_beam_4.dcm')"

      - name: Build documentation
        run: |
          uv run pymedphys dev docs

          uv run python -m sphinx.ext.linkcheck lib/pymedphys/docs || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # 4.0.0
        with:
          path: lib/pymedphys/docs/_build/html

  deploy:
    needs: [build]
    if: ${{ inputs.publish }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # 4.0.5
