name: docs

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        with:
          python-version: "3.12"
          cache-key-suffix: docs
      - name: Install docs deps
        shell: bash
        run: |
          uv pip install -e ".[docs]" --system
      - name: Build docs
        shell: bash
        run: |
          set -euxo pipefail
          if [[ -f docs/Makefile ]]; then
            make -C docs html
            echo "out=docs/_build/html" >> $GITHUB_OUTPUT
          elif [[ -f mkdocs.yml ]]; then
            uv pip install mkdocs mkdocs-material --system
            mkdocs build
            echo "out=site" >> $GITHUB_OUTPUT
          else
            echo "No docs configuration found" >&2
            exit 1
          fi
        id: build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.build.outputs.out }}

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
