name: Lint & Format

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ruff:
    name: Ruff (lint & format)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-project
        with:
          python-version: '3.13'
          extras: ''  # Minimal dependencies for linting

      - name: Run ruff check
        run: |
          uv run ruff check --output-format=github

      - name: Run ruff format check
        run: |
          uv run ruff format --check --diff

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-project
        with:
          python-version: '3.13'
          extras: 'dev tests'

      - name: Run pylint
        run: |
          uv run pymedphys dev lint
