name: Lint & Format

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Ruff (lint & format)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-project
        with:
          extras: "lint"

      - name: Run ruff check
        run: |
          uv run ruff check --output-format=github

      - name: Run ruff format check
        run: |
          uv run ruff format --check --diff

      - name: Run pylint
        run: |
          uv run pymedphys dev lint
