# Copyright (C) 2025 Matthew Jennings

name: Lint & Format

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Pylint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-project
        with:
          extras: 'all'

      - name: Run pylint
        run: |
          uv run pymedphys dev lint
