name: pre-commit

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        with:
          python-version: "3.12"
          cache-key-suffix: precommit
      - name: Install hooks deps
        shell: bash
        run: uv pip install pre-commit --system
      - name: Run pre-commit
        shell: bash
        run: uv run pre-commit run --all-files --show-diff-on-failure
