name: release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build dists
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        with:
          python-version: "3.12"
          cache-key-suffix: release
      - name: Build sdist/wheels
        shell: bash
        run: |
          uv pip install build --system
          uv run python -m build
      - name: Upload dists
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error

  publish:
    name: Publish to PyPI (OIDC)
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: pypi
      # optional: set URL to project page for nicer env card on runs
      url: https://pypi.org/p/pymedphys
    permissions:
      id-token: write  # REQUIRED for Trusted Publishing
      contents: read
    steps:
      - name: Download dists
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # Pin to a full commit SHA (v1.13.0)
      # PyPA recommends pinning to a tag or full commit SHA; we use a SHA here.
      - name: Publish
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1.13.0
        with:
          # attestations are ON by default for Trusted Publishing in recent versions
          # repository-url: https://test.pypi.org/legacy/  # (for TestPyPI)
          # skip-existing: true
          verbose: true
