name: Security Scan

on:
  pull_request:
    paths:
      - 'pyproject.toml'
      - 'uv.lock'
  schedule:
    - cron: '0 0 * * MON'
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-project
        with:
          extras: 'all'

      - name: Scan for Anthropic API key exposure
        run: |
          ! grep -r --include="*.py" --include="*.yml" --include="*.yaml" \
            -E '(print|log|console\.log|echo).*ANTHROPIC' .
          ! grep -r --include="*.py" \
            -E '(requests\.get|requests\.post|fetch).*\$\{?ANTHROPIC' .

      - name: Dependency audit
        run: |
          uv sync --frozen
          uv pip audit

      - name: Run Bandit
        run: |
          uv pip install bandit[toml]
          uv run -- bandit -r pymedphys/ -f sarif -o bandit.sarif || true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

      - name: Run Trivy
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # pin for security
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy.sarif

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
