name: Security Scan

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

concurrency:
  group: security-${{ github.ref }}
  cancel-in-progress: false

jobs:
  secret-scan:
    name: Scan for secrets and key exposure
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Fast OSS scan; fails on leak; uploads SARIF
      - name: Run gitleaks
        shell: bash
        run: |
          set -euxo pipefail
          pipx install gitleaks || python -m pip install gitleaks
          gitleaks detect --redact --report-format sarif --report-path gitleaks.sarif || EXIT=$?
          echo "exit=${EXIT:-0}" >> $GITHUB_OUTPUT

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
