name: Type Check

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  pyright:
    name: Pyright
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - uses: ./.github/actions/setup-project
        with:
          extras: "dev tests"

      - name: Run pyright
        run: |
          uv run -- pyright

  mypy:
    name: MyPy (optional)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    continue-on-error: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2

      - uses: ./.github/actions/setup-project
        with:
          extras: "dev tests"

      - name: Run mypy
        run: |
          uv run -- mypy --install-types --non-interactive pymedphys || true
